layout of the login page
open-schools/open-schools-platform-frontend pull request #3
Opened 2023-06-29 16:04 UTC by Rey-2903

2023-07-10 11:30 UTC, levil664 reviewed
![image](https://github.com/LamArt/open-schools-platform-frontend/assets/56757711/da3fb11b-0332-4e1d-ae18-734e37984dbd)
![image](https://github.com/LamArt/open-schools-platform-frontend/assets/56757711/d8093db7-cb3f-4a61-be6a-a8c116415344)

why, when restoring a password, I have to register, and not just restore the password according to the figma

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Anchor/index.tsx
> +}
need ...restProps like these
```
import { ButtonHTMLAttributes } from 'react'

interface CustomButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'> {
    type?: 'schoolDefault' | 'schoolGradient';
    antdType?: ButtonProps['type'];
}

export const Button: React.FC<CustomButtonProps> = (props) => {
    const { type = 'schoolDefault', antdType, ...restProps } = props
```

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Anchor/index.tsx
> +
are needed ...otherProps

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Anchor/index.tsx
> +}
must be in constants folder

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Button/index.tsx
> +    'schoolGradient': gradientStyles,
we use gradient styles?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Anchor/index.tsx
> +}
or these 
```
import { ButtonProps } from 'antd'

interface CustomButtonProps extends Omit<ButtonProps, 'type'> {
    type?: 'schoolDefault' | 'schoolGradient',
    antdType?: ButtonProps['type'],
    onClick?: () => void,
    text?: string,
}


export const Button: React.FC<CustomButtonProps> = (props) => {
    const { type = 'schoolDefault', antdType = 'primary', onClick, ...restProps } = props
```

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CentralizingContainer/index.tsx
> +export const CentralizingContainer: React.FC<any> = (props: PropsWithChildren<any>) => {
there shouldn't be any

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CentralizingContainer/index.tsx
> +export const CentralizingContainer: React.FC<any> = (props: PropsWithChildren<any>) => {
somehow, but we should avoid any

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CentralizingContainer/index.tsx
why CentralizingContainer in common domain? And if it should be here, make it normally reused with ...restProps.

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CentralizingContainer/index.tsx
> +            <Row justify='center' align="middle" className={styles.fullHeight}>
fullHeight? And if we have to add something else?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CentralizingContainer/styles/styles.module.scss
> +.fullHeight{
^^

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
why CountDownTimer in common domain? And if it should be here, make it normally reused with ...restProps.

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +import { timer } from '../../utils/timer'
why are there spaces between imports?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +const DEFAULT_TIMEOUT = 60 // s
must be in constants

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +}
must be in utils

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +}
^^

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +}
we have an Interfaces folder

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +    }, [])
looks like must be in utils or tasks folder

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +    }
^^

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Input/index.tsx
> +}
we have an Interfaces folder

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Input/index.tsx
> +const BUTTON_INPUT_PHONE_STYLE: React.CSSProperties = { margin: 5, backgroundColor: '#E6E8F1', border: 0, borderRadius: 8 }
styles.module.scss?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Input/index.tsx
> +                    inputStyle={INPUT_PHONE_STYLE}
^^

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Link/index.tsx
> +}
need ...restProps like these
```
import { ButtonHTMLAttributes } from 'react'

interface CustomButtonProps extends Omit<ButtonHTMLAttributes, 'type'> {
type?: 'schoolDefault' | 'schoolGradient';
antdType?: ButtonProps['type'];
}

export const Button: React.FC = (props) => {
const { type = 'schoolDefault', antdType, ...restProps } = props
```

or these
```
import { ButtonProps } from 'antd'

interface CustomButtonProps extends Omit<ButtonProps, 'type'> {
type?: 'schoolDefault' | 'schoolGradient',
antdType?: ButtonProps['type'],
onClick?: () => void,
text?: string,
}

export const Button: React.FC = (props) => {
const { type = 'schoolDefault', antdType = 'primary', onClick, ...restProps } = props
```

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Link/index.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Anchor/index.tsx
> +
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Button/index.tsx
>  }
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +const setCountDownDate = (date: any, countDownId: any) => {
we should not use any

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/Link/styles/underlining.module.scss
> +}
for what?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/utils/helpers.ts
> +
why two spaces?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/utils/helpers.ts
> +const PHONE_FORMAT_REGEXP = /(\d)(\d{3})(\d{3})(\d{2})(\d{2})/
constants folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/utils/helpers.ts
> +type UpdateQueryType = (router: NextRouter, data: Partial<IUpdateQueryData>, options?: Partial<IUpdateQueryOptions>) => Promise<void>
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/utils/helpers.ts
> +    const newParameters: any = get(data, 'newParameters', {})
we should not use any

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/utils/timer.ts
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/FormContainer/index.tsx
are we sure we don't need ...restProps in domains except common?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/FormContainer/index.tsx
> +export const FormContainer: React.FC<any> = (props: PropsWithChildren<any>) => {
we must not use any

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/FormContainer/styles/styles.module.scss
empty

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/HeaderActions/index.tsx
> +}
must be in interface folder

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/HeaderActions/index.tsx
> +    const signInTab = 'Вход'
why won 't we put it in constants?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/RegisterForm/RegisterForm.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/RegisterForm/RegisterForm.tsx
> +const BUTTON_FORM_GUTTER: RowProps['gutter'] = [0, 40]
constants folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/RegisterForm/RegisterForm.tsx
> +import { useRegisterFormValidators } from './hooks'
why this import here?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +    const startTimer = React.useCallback((duration) => {
why is it react.useCallback and not just useCallback

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/common/components/CountDownTimer/index.tsx
> +    const startTimer = React.useCallback((duration) => {
in other places you used useCallback

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/RegisterForm/hooks.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/RegisterForm/hooks.tsx
hooks folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/ResetForm/ResetForm.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/ResetForm/ResetForm.tsx
> +const BUTTON_FORM_GUTTER: RowProps['gutter'] = [0, 40]
constants folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/ResetForm/ResetForm.tsx
> +import { useResetFormValidators } from './hooks'
why this import here?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/ResetForm/hooks.tsx
hooks folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/ResetForm/hooks.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/SharedForms/InputPhoneForm.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/SharedForms/ValidatePhoneForm.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/SharedForms/ValidatePhoneForm.tsx
> +const FORM_ITEMS_GUTTER: RowProps['gutter'] = [0, 24]
constants folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/SharedForms/ValidatePhoneForm.tsx
> +const INPUT_STYLE: CSSProperties = { maxWidth: '120px' }
styles.module.scss?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/SignInForm/styles/styles.module.scss
empty

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/auth/SharedForms/ValidatePhoneForm.tsx
> +    }, [confirmPhone])
we have tasks folder for async and callback functions.

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/containers/AuthLayout.tsx
> +}
interfaces and constants folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/domains/user/components/containers/AuthLayout.tsx
> +} /* = getConfig() */ = { publicRuntimeConfig: { HelpRequisites: { support_email: 'openschools@education', support_phone: '+79999999999' } } }
constants folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/pages/_app.tsx
> +}
interfaces folder?

2023-07-10 11:30 UTC, levil664 commented on apps/schools/pages/auth/forgot.tsx
> +    }
constants folder?

2023-07-10 11:31 UTC, levil664 reviewed
![image](https://github.com/LamArt/open-schools-platform-frontend/assets/56757711/da3fb11b-0332-4e1d-ae18-734e37984dbd)
![image](https://github.com/LamArt/open-schools-platform-frontend/assets/56757711/d8093db7-cb3f-4a61-be6a-a8c116415344)

why, when restoring a password, I have to register, and not just restore the password according to the figma

2023-07-10 11:32 UTC, levil664 requested changes
there are too many comments they should be filtered out or deleted

2023-07-10 12:38 UTC, levil664 commented on apps/schools/domains/user/components/containers/AuthLayout.tsx
> +                style={{ backgroundImage: 'url(/image/authImage.svg)' }}
scss?

2023-07-10 14:02 UTC, mzavarka commented on apps/schools/domains/common/components/Button/index.tsx
> +    'schoolGradient': gradientStyles,
we don't use them but
it is example styles

2023-07-12 12:52 UTC, levil664 approved these changes

2023-07-12 13:03 UTC, levil664 approved these changes

2023-07-12 13:13 UTC, merged